development:
    STATIC_ROOT: .

    STATIC_URL: /static/

    TIME_ZONE: America/Sao_Paulo

    LANGUAGE_CODE: pt-br

    INSTALLED_APPS:
        - django.contrib.admin
        - django.contrib.auth
        - django.contrib.contenttypes
        - django.contrib.sessions
        - django.contrib.messages
        - django.contrib.staticfiles
        - rest_framework
        - apps.blog

